security:
    # Password hashers for Symfony 5.3 and above
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    # User provider configuration
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Firewall configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Remove anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
            lazy: true
            provider: app_user_provider

    # Access control rules
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/tournaments, roles: ROLE_ORGANIZER }
        - { path: ^/users, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow anonymous access to login

